import"./assets/script-176bfda7.js";import{T as c}from"./assets/tabs-0d1d1a23.js";let o=document.getElementById("gungs");async function p(a){let s=new FormData;return console.log(a),s.append("firstVisit",a.firstVisit),s.append("type",a.type),await(await fetch("/local/ajax/main/weapons.php",{method:"POST",body:s})).json()}const d=a=>{o.innerHTML="",a.forEach(s=>{o.insertAdjacentHTML("afterBegin",`<div class="p-[18px_18px_24px_18px] sm:p-[18px_18px_32px_18px] flex flex-col items-start sm:items-center gap-6 sm:gap-8 bg-[#1A1A19]">
  <div class="py-8 px-[60px] sm:p-[43px_78px_42px_81px] bg-[#222220] w-[294px] sm:w-[380px]"><img class="w-[220px] h-[150px]" src=${s.avatar}></div>
  <div class="max-w-[283px] sm:max-w-[350px]">
    <h3 class="sm:text-xl text-base font-medium leading-4 sm:leading-6 text-white mb-[18px]">${s.name}</h3>
    <p class="sm:text-base text-sm font-normal leading-[140%] text-[rgba(_255,_255,_255,_0.40)] mb-6">Программы, включающие обучение навыкам безопасного обращения с оружием, меткой и быстрой стрельбы...</p>
    <a href="#" class="inline-block sm:text-base text-sm font-normal underline text-white mb-6">Подробнее</a>
    <div class="w-full h-[1px] bg-[#2D2D2B]"></div>
  </div>
  <div class="flex justify-between items-center gap-x-4 sm:gap-16">
    <p class="text-white text-base sm:text-xl font-normal leading-6">20 500 ₽</p>
    <button class="flex justify-center items-start py-[18px] px-9 bg-[#272723] text-white text-base btn font-normal">Забронировать</button>
  </div>
</div>
      `)})},m=()=>{let a=document.querySelectorAll("[data-gun]"),s=document.querySelector('[data-filter="false"]'),t=a[0];s.addEventListener("click",async e=>{e.target.closest(".btn__custom")&&e.target.closest(".btn__custom").classList.toggle("active"),e.currentTarget.dataset.filter==="false"?e.currentTarget.setAttribute("data-filter",!0):e.currentTarget.setAttribute("data-filter",!1);let i=await p({firstVisit:s.dataset.filter,type:t==null?void 0:t.dataset.gun});d(i)}),document.querySelector(".nav-gung").addEventListener("click",async e=>{let i=e.target.closest(".btn__custom");i&&(t===i?(t.classList.remove("active"),t=void 0):(t==null||t.classList.remove("active"),t=i,t.classList.add("active")));let n=await p({firstVisit:s.dataset.filter,type:t==null?void 0:t.dataset.gun});d(n)})};m();document.addEventListener("DOMContentLoaded",()=>{const a=t=>{let e=t.querySelector(".swiper-pagination-bullet-active"),i=[...t.querySelectorAll(".swiper-pagination-bullet")],n=i.indexOf(e);i.forEach((r,l)=>{n+1!==l&&n-1!==l&&n!==l?r.classList.add("acti"):r.classList.remove("acti")})};let s=new Swiper(".mySwiper",{slidesPerView:3,spaceBetween:30,breakpoints:{320:{slidesPerView:1,spaceBetween:20},750:{slidesPerView:"auto",spaceBetween:28}},pagination:{el:".pagination__custom",dynamicBullets:!0,clickable:!0,renderBullet:function(t,e){return`<div class="${e}">
            <span>0${t+1}</span>
          </div>`}},navigation:{nextEl:".custom-next",prevEl:".custom-prev"}});a(s.pagination.el),s.on("paginationRender",function(t,e){a(e)}),new Swiper(".myGallerey",{navigation:{nextEl:".myGallerey-custom-next",prevEl:".myGallerey-custom-prev"}}),c(".galleries__tabs",".tabs__head",".tabs__body",".tabs__caption","tabs__caption_active","tabs__content_active"),c(".route__tabs",".tabs__head",".tabs__body",".tabs__caption","tabs__caption_active","tabs__content_active")});
